default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.54.0
    hooks:
      - id: eslint
        name: eslint (Gourami UI)
        types: [file]
        files: "^(.*).[jt]sx?$"
        args:
          [
            "--parser-options",
            "sourceType:module",
            "--parser-options",
            "ecmaVersion:2023",
            "--fix",
            "--quiet",
          ]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
